[최상현] Assignment 6, 7, 8: Express API - CRUD(2)
wecode-bootcamp-korea/44-backend-westagram-2 pull request #23
Opened 2023-03-24 13:42 UTC by Dongrang072

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지

patched 과정
![스크린샷(15)](https://user-images.githubusercontent.com/52373572/227536282-4cbdd009-e98c-41f4-b34a-c8a40fb3844f.png)
![스크린샷(16)](https://user-images.githubusercontent.com/52373572/227536310-9a417283-f6bd-40cd-9054-2349ae1a4d7d.png)
![스크린샷(17)](https://user-images.githubusercontent.com/52373572/227536321-53f804ad-0566-4a10-b387-41997e23fff5.png)
![스크린샷(18)](https://user-images.githubusercontent.com/52373572/227536347-a812e2c0-5740-46d3-932c-59362252eac7.png)

delete 과정

![스크린샷(19)](https://user-images.githubusercontent.com/52373572/227536542-62b96b64-fa7a-4f02-9af6-2884791ccc0c.png)

![스크린샷(20)](https://user-images.githubusercontent.com/52373572/227536567-65858d15-25be-482c-9692-71fdc3eeb1a6.png)
![스크린샷(21)](https://user-images.githubusercontent.com/52373572/227536603-5406c853-c57e-4ad9-b230-edcfcb0874a4.png)
![스크린샷(22)](https://user-images.githubusercontent.com/52373572/227536632-593b339d-c069-4c57-9fa3-3e851812883e.png)

like 과정
![스크린샷(23)](https://user-images.githubusercontent.com/52373572/227536710-c5696c0f-8f0a-4d70-9770-40ed4f1d953c.png)

![스크린샷(24)](https://user-images.githubusercontent.com/52373572/227536725-f2b5697f-d7c2-4044-90ff-85a54cd2de34.png)
![스크린샷(25)](https://user-images.githubusercontent.com/52373572/227536738-645d0bbe-ef35-42ed-a757-e1835ada7245.png)

![스크린샷(26)](https://user-images.githubusercontent.com/52373572/227536765-38bc1c4e-6eeb-4f01-94f8-7efd438ac0dd.png)

<br />

## :: 기타 질문 및 특이 사항
- unique key로 묶여서 생성된 likes에 특정 user의 id나 post의 key값을 가진 
로우가 존재하면,  posts나 users에서 그 해당 키값을 가진 로우를 삭제할 수 없었습니다. 
원리를 아직 잘 모르겠습니다.  설명해주시면 감사하겠습니다

2023-03-25 06:58 UTC, Kang-kyunghun requested changes
conflict가 나있습니다. conflict 해결해 주세요.

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/app.js
> +
불필요한 공백 제거해 주세요.

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/app.js
> +
불필요한 공백 제거해 주세요.

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/app.js
> +
구문 사이에 공백은 1칸만 주시면 좋을 것 같습니다.
불필요한 공백 제거해 주세요.

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/app.js
> +app.get("/postings/:userId", async (req, res) => {
해당 코드부터 들여씌기 간격이 달라진 것 같은데 확인해 주시고, 위의 코드와 같은 간견의 들여씌기로 맞춰주세요.

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/app.js
> +  app.delete("/delete", async (req, res) => {
불필요한 공백 제거해 주세요.
```suggestion
      [postId]
    );
   
    res.status(200).json({ message: "patched done", data: (patchedData) });
  });

  app.delete("/delete", async (req, res) => {
```

2023-03-25 06:58 UTC, Kang-kyunghun commented on Sanghyun/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
해당 파일은 github에 올라오지 않게 gitignore에 추가해 주세요.

2023-03-27 01:39 UTC, Jon9Beom commented
상현님! 컨플릭트 해결해주세요. 혹시 컨플릭트 해결하는 방법이 헷갈리신다면 찾아와주세요!

2023-03-27 07:15 UTC, merged