[44기 임성근][ADD]:Express 초기 환경세팅
wecode-bootcamp-korea/44-backend-westagram-2 pull request #5
Opened 2023-03-22 06:05 UTC by lsg622

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 개발 초기환경 설정

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express 설치 / 적용
- nodemon 설치 / 적용
- cors 설치 / 적용
- dotenv 설치 / 환경 변수 적용
- morgan 설치 / 적용
- TypeORM 설치 및 적용
- dbConnection 정상 작동 확인

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![server](https://user-images.githubusercontent.com/123074891/226815570-efeb0e11-ce0a-449a-922c-e8a3af85c46a.jpeg)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![ping](https://user-images.githubusercontent.com/123074891/226816248-f9e42857-407e-4321-a67a-8bb72a42df43.jpeg)

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-03-22 06:57 UTC, Kang-kyunghun requested changes

2023-03-22 06:57 UTC, Kang-kyunghun commented on seong-geun/app.js
> +const myDataSource = new DataSource({
myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

```suggestion
const appDataSource = new DataSource({
```

2023-03-22 06:57 UTC, Kang-kyunghun commented on seong-geun/app.js
> +});
추가로 dataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2023-03-22 06:57 UTC, Kang-kyunghun commented on seong-geun/app.js
> +// });
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2023-03-22 06:57 UTC, Kang-kyunghun commented on seong-geun/package.json
> +    "typeorm": "^0.3.12"
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql2, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
- mysql2 패키지가 빠진 것 같습니다. 추가로 설치해 주세요.

2023-03-23 02:37 UTC, Jon9Beom commented on seong-geun/.env.sample
> +DB_LOGGING = TRUE
- dbmate 연결 목적의 DATABASE_URL에는 개인이 로컬 환경에서 어떠한 rdbms를 쓰는지 그 힌트가 될 수 있는 단어와, 포트번호 대신 중의적인 단어를 대신 사용하여 환경변수에 대한 format을 작성해주세요.
    
    ```jsx
    // Example	
    
    DATABASE_URL="rdbmsType://username:password@iphost:portNumber/databaseName"
    ```

2023-03-23 02:37 UTC, Jon9Beom commented on seong-geun/app.js
> +const http = require("http");
```suggestion
```
express를 사용할 때에는 node.js built-in module인 `http` 모듈을 사용하지 않습니다. http 모듈은 네트워크 요청을 처리할 수 있도록 도와주는 도구라고 생각하시면 되는데 express라는 웹 프레임워크를 사용함으로써 http 모듈보다 더 쉽고 유연하게 네트워크 요청을 처리할 수 있습니다.

2023-03-23 02:37 UTC, Jon9Beom commented on seong-geun/app.js
> +dotenv.config();
```suggestion
require("dotenv").config();
```
두줄로 작성된 기존 코드를 변수 선언 없이 한줄로써 작성될 수 있습니다.

2023-03-23 02:37 UTC, Jon9Beom commented on seong-geun/app.js
> +const server = http.createServer(app);
```suggestion
```
마찬가지로 http 모듈을 사용하지 않기 때문에 필요하지 않은 코드입니다.

2023-03-23 02:37 UTC, Jon9Beom commented on seong-geun/app.js
> +  server.listen(PORT, () => console.log(`server is listening on ${PORT}`));
```suggestion
  app.listen(PORT, () => console.log(`server is listening on ${PORT}`));
```
http 모듈을 활용한 server라는 변수 대신, express를 활용하여 위에서 선언한 app이라는 실행시키도록 작성해주세요~

2023-03-23 05:28 UTC, Jon9Beom commented
LGTM 👍

2023-03-23 05:28 UTC, merged